language: cpp

dist: trusty

compiler:
  - gcc

os:
  - linux

before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt571-trusty
  - sudo apt-get -qq update
  - sudo apt-get install -qy libxcb-keysyms1-dev qt57-meta-minimal qt57quickcontrols2 qt57quickcontrols

script:
  - source /opt/qt57/bin/qt57-env.sh
  - qmake -v
  - qmake puush-qt.pro
  - make
