version: build{build}

image:
  - Visual Studio 2017
  - Ubuntu

init:
  - cmd: set PATH=C:\Qt\5.12\msvc2017_64\bin;%PATH%
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

install:
  - sh: sudo add-apt-repository -y ppa:beineri/opt-qt-5.10.1-xenial
  - sh: sudo apt-get -qq update
  - sh: sudo apt-get -qqy install mesa-common-dev libxcb-keysyms1-dev qt510{-meta-minimal,quickcontrols2,quickcontrols} > /dev/null
  - sh: source /opt/qt510/bin/qt510-env.sh

before_build:
  - cmd: cd C:\projects\puush-qt
  - git submodule update --init
  - mkdir build

build_script:
  - cd build
  - cmd: cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..
  - sh: cmake -DMakeDeb=On -DCMAKE_BUILD_TYPE=Release ..
  - cmd: nmake
  - sh: make

after_build:
  - cmd: nmake package
  - sh: make package
  # Appimage setup
  - sh: make DESTDIR=root install
  - sh: wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - sh: chmod +x linuxdeployqt*.AppImage
  - sh: unset QTDIR; unset QT_PLUGIN_PATH; unset LD_LIBRARY_PATH
  # Add some libraries that don't get detected
  - sh: mkdir -p root/usr/local/{qml/QtQuick,plugins}
  - sh: cp -r /opt/qt510/qml/QtQuick/Dialogs root/usr/local/qml/QtQuick
  - sh: cp -r /opt/qt510/plugins/xcbglintegrations root/usr/local/plugins
  # Run linuxdeployqt to find libaries and make appimage
  - sh: ./linuxdeployqt*.AppImage root/usr/local/share/applications/puush-qt.desktop -qmldir=/opt/qt510/qml -bundle-non-qt-libs -appimage

artifacts:
  - path: build\puush-qt-*-win64.zip
    name: zip
  - path: build\puush-qt-*-win64.exe
    name: installer
  - path: build\puush-qt-*-Linux.tar.gz
    name: tarball
  - path: build\puush-qt-*-Linux.sh
    name: self extracting shell script
  - path: build\puush-qt-*-Linux.deb
    name: debian package
  - path: build\puush-qt*.Appimage
    name: appimage
